/****************************************************************************/
/* Kbd                                                                      */
/* Simple Handler                                                           */
/****************************************************************************/
#define KBD_ESC 1
#define KBD_ENTER 28
#define KBD_SPACE 57
#define KBD_LEFT 75
#define KBD_RITE 77
#define KBD_UP 72
#define KBD_DOWN 80
#define KBD_PLUS 78
#define KBD_MINUS 74
#define KBD_F1 59
#define KBD_F2 60
#define KBD_F3 61
#define KBD_F4 62
#define KBD_F5 63
#define KBD_F6 64
#define KBD_F7 65
#define KBD_F8 66
#define KBD_F9 67
#define KBD_F10 68
